<a href="https://colab.research.google.com/github/KuhQianYu-2025/data-science-toolkit-w1/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.array([[1,2],[3,4]])
print("A numpy array of size 2 x 2: \n", a)

A numpy array of size 2 x 2: 
 [[1 2]
 [3 4]]


In [20]:
b = np.random.randint(1,20,size=(3,4))
print("A random numpy array of size 3 x 4:\n", b)

A random numpy array of size 3 x 4:
 [[10  8  2  8]
 [15 18 12 10]
 [ 6  8 13 16]]


In [25]:
c = np.ones((3,4))
d = np.zeros((2,5))

print("A numpy array of ones:\n", c)
print("A numpy array of zeros:\n", d)

A numpy array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A numpy array of zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
e = np.random.randint(1,20,size=(6,3))
eTransposed = e.T

print("Transpose of a (6x3) random numpy array:\n", eTransposed)

Transpose of a (6x3) random numpy array:
 [[17 13 10 16  6  3]
 [11 13 16 15  6 13]
 [18 14 18 10 13 11]]


In [28]:
n=3
p=4
m=5

f = np.array([n,p])
g = np.array([p,m])
print("Array 1(n x p):\n", f)
print("Array 2(p x m):\n", g)

dotproduct = f @ g
print("The dot product of f(nxp) and g(pxm):\n",dotproduct)

Array 1(n x p):
 [3 4]
Array 2(p x m):
 [4 5]
Shape of B: (2,)
The dot product of f(nxp) and g(pxm):
 32
